[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "linker=gcc",
    "-C", "link-arg=-fuse-ld=bfd",
    "-C", "link-arg=-static",
    "-C", "link-arg=-no-pie",
    "-C", "link-arg=-luacpi",
    "-C", "link-arg=-Wl,--gc-sections",
]